package ro.ainpc.world.patch;

public enum PatchGapType {
    MISSING_BEDS,
    MISSING_HOUSE_CAPACITY,
    MISSING_WORKPLACE_FOR_PROFESSION,
    MISSING_SOCIAL_HUB,
    MISSING_QUEST_TRIGGER_NODE,
    MISSING_ENTRANCE_NODE,
    HOUSE_TOO_SMALL_FOR_FAMILY,
    WORKPLACE_WITHOUT_WORK_NODE
}
